### ISSUE TITLE
Compilation issue with gcc14 and nginx 1.27.0

### ISSUE THREAD

**Issue by satmd** [owasp-modsecurity/ModSecurity-nginx#325]
This module does not compile on my gentoo unstable gcc14 amd64 system, because of using printf() without including stdio.h:

Patch included below.
[http_security-1.3.0-gcc14.patch.txt](https://github.com/user-attachments/files/15885283/http_security-1.3.0-gcc14.patch.txt)

Sorry for not providing a regular PR.

**Comment by satmd** [comment]
Downstream bug: https://bugs.gentoo.org/933598

**Comment by airween** [comment]
Hi @satmd,

thanks for reporting.

Unfortunately this is an "old" issue (therefore this is a duplicated report) - there is a similar solution in #275.

I'm going to close this one - thanks again.
